name = "api"
main = "src/index.ts"
compatibility_date = "2023-12-01"

r2_buckets = [
  { binding = "Content", bucket_name = "content", preview_bucket_name = "content" },
  { binding = "Data", bucket_name = "data", preview_bucket_name = "data" }
]

[[d1_databases]]
binding = "DB"
database_name = "submissions"
database_id = "6d00eb71-b420-47f7-9e74-96d53bcb943a"

[[analytics_engine_datasets]]
binding = "Analytics"
